services:
  # Backend API service
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: RECIPIENT_EMAIL
        sync: false
      - key: PORT
        value: 3000

  # Frontend web service
  - type: web
    name: portfolio-frontend
    env: node
    buildCommand: npm install -g serve && serve -s .
    startCommand: serve -s . -l $PORT
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: BACKEND_URL
        value: https://portfolio-backend-8q07.onrender.com
      - key: PORT
        value: 10000 